### ISSUE TITLE
Query engine fails selecting DBMS_CRYPTO.HASH value

### ISSUE THREAD

**Issue by pgoldtho** [visulate/visulate-for-oracle#188]
Example
```
select DBMS_CRYPTO.HASH(rawtohex('12345') ,2) as CHECKSUM from dual
```

**Comment by pgoldtho** [comment]
INFO in sql2csv: POST RNTMGR2 @ vis13: select DBMS_CRYPTO.HASH(rawtohex('12345') ,2) as CHECKSUM
from dual

INFO in __init__: 127.0.0.1 [23/Sep/2020:14:43:25.585] POST /sql/vis13 http 200 OK None http://localhost:4200/database/vis13/RNTMGR2/TABLE/RNT_ACCOUNTS?filter=RNT_* Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
INFO in _internal: 127.0.0.1 - - [23/Sep/2020 10:43:25] "POST /sql/vis13 HTTP/1.1" 200 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/sql2csv/sql2csv.py", line 162, in generate
    yield(json.dumps(row, default=str))
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/pgoldtho/git/visulate-for-oracle/query-engine/venv/lib/python3.8/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte
